package com.example.project.measurements;

import java.io.File;
import java.net.URL;
import java.sql.*;
import java.time.LocalDate;
import java.util.ResourceBundle;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.ComboBox;
import javafx.scene.control.DatePicker;
import javafx.scene.control.TextArea;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.stage.FileChooser;

import static com.example.project.alert.showMymsg;
import static com.example.project.sqlConnector.mySqlConnector.doConnect;

public class MeasurementsController {

    String[] clothingTypes = {
            "Shirt",
            "Pants",
            "Suit",
            "Blouse",
            "Skirt",
            "Dress",
            "Coat",
            "Jacket",
            "Vest",
            "Jeans",
            "Shorts",
            "Overcoat",
            "Waistcoat",
            "Tuxedo",
            "Saari",
            "Shervani",
            "Kurta"
    };

    Connection con;
    PreparedStatement stmt;

    @FXML
    private ResourceBundle resources;

    @FXML
    private URL location;

    @FXML
    private ComboBox<String> comboDress;

    @FXML
    private ComboBox<String> comboWorkers;

    @FXML
    private ImageView imageview;

    @FXML
    private TextField txtBill;

    @FXML
    private TextField txtCustomerMobile;

    @FXML
    private DatePicker txtDateOfDelivery;

    @FXML
    private TextArea txtMeasurementsOthers;

    @FXML
    private TextField txtPricePerUnit;

    @FXML
    private TextField txtQuantity;

    @FXML
    void doAddWorker(){
        try{
            stmt = con.prepareStatement("select wname from workers where splz like ?");
            String cloth = comboDress.getSelectionModel().getSelectedItem();
            stmt.setString(1,"%"+cloth+"%");
            ResultSet res = stmt.executeQuery();
            comboWorkers.getItems().clear();
            while (res.next()) {
                comboWorkers.getItems().add(res.getString("wname"));
            }
        }
        catch (Exception exp){
            exp.printStackTrace();
        }
    }

    @FXML
    void doClear(ActionEvent event) {

    }

    @FXML
    void doClose(ActionEvent event) {

    }

    String selectedImagePath = "";
    int bill;


    @FXML
    public void doCalc() {
        bill = 0;
        bill = Integer.parseInt(txtQuantity.getText())*Integer.parseInt(txtPricePerUnit.getText());
        txtBill.setText(String.valueOf(bill));
    }

    @FXML
    void doSave(ActionEvent event) {
        try{
            doCalc();
            stmt = con.prepareStatement("insert into measurements values(null,?,?,?,?,?,?,?,?,current_date())",Statement.RETURN_GENERATED_KEYS);
            stmt.setString(1,txtCustomerMobile.getText());
            stmt.setString(2,comboDress.getSelectionModel().getSelectedItem());
            stmt.setString(3,selectedImagePath);
            LocalDate dt =txtDateOfDelivery.getValue();
            java.sql.Date ddl = java.sql.Date.valueOf(dt);
            stmt.setDate(4,ddl);
            stmt.setInt(5,Integer.parseInt(txtQuantity.getText()));

            txtBill.setText(String.valueOf(bill));
            stmt.setInt(6,bill);
            stmt.setString(7,txtMeasurementsOthers.getText());
            stmt.setString(8,comboWorkers.getSelectionModel().getSelectedItem());
            int rowsaffected = stmt.executeUpdate();
            if(rowsaffected>0){
                try {
                    ResultSet res = stmt.getGeneratedKeys();
                    if (res.next()){
                        long autoGeneratedId = res.getLong(1);
//                        System.out.println("Auto Generated ID: " + autoGeneratedId);
                        showMymsg("OrderId : "+autoGeneratedId);
                    }
                }
                catch (Exception exp){
                    exp.printStackTrace();
                }
            }

        }
        catch(Exception exp){
            exp.printStackTrace();
        }


    }

    @FXML
    void doUpdate(ActionEvent event) {

    }

    @FXML
    void doUpload(ActionEvent event) {
        FileChooser fileChooser = new FileChooser();
        fileChooser.setTitle("Choose an image");
        fileChooser.setInitialDirectory(new File("C:\\"));
        fileChooser.getExtensionFilters().addAll(new FileChooser.ExtensionFilter("All Images","*.jpg","*.png"));
        File selectedFile = fileChooser.showOpenDialog(null);

        if(selectedFile != null)
        {
            Image image = new Image(selectedFile.toURI().toString());
            imageview.setImage(image);
        }
        else
            System.out.println("No file selected");
        selectedImagePath = selectedFile.toURI().toString();
    }

    @FXML
    void initialize() {
        con = doConnect();
        if(con==null)
            System.out.println("sorry");
        else
            System.out.println("Congo");

        comboDress.getItems().addAll(clothingTypes);
    }

}
